schema_version: "1.0"
id: 3x_healing
display_name: 3x Healing
short_description: Triples base healing rate.
author:
  - Shard
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/Medium-Maintenance-Small-Mods/3x_healing
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/Medium-Maintenance-Small-Mods/3x_healing
categories:
  - rebalance
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
