schema_version: "1.0"
id: animatronic_monsters
display_name: Animatronic Monsters
short_description: >-
  Adds a chain of bankrupt pizzerias, with still functioning animatronics
  inside.
author:
  - Lanceo90
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Animatronics
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Animatronics
categories:
  - buildings
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
