schema_version: "1.0"
id: arcana_dinomod_patch
display_name: Arcana/DinoMod Patchmod
short_description: >-
  Optional patch mod that allows content in Arcana and DinoMod to interact with
  each other.
author:
  - Chaosvolt
license: CC-BY-SA-3.0
homepage: >-
  https://github.com/chaosvolt/cdda-arcana-mod/tree/master/Patchmods/BN_Arcana_Dinomod_Patch
version: 0.0.0
source:
  type: github_archive
  url: "https://github.com/chaosvolt/cdda-arcana-mod/archive/refs/heads/master.zip"
  commit_sha: 37718985431bdbfbee1488e23747edbed3440cbf
  extract_path: Patchmods/BN_Arcana_Dinomod_Patch
categories:
  - misc_additions
dependencies:
  bn: ">=0.9.1"
  arcana: "*"
  dinomod: "*"
autoupdate:
  type: commit
  branch: master
last_updated: "2025-12-08T17:38:23.169Z"
parent: arcana
