schema_version: "1.0"
id: arcana_cata_patch
display_name: Arcana/Cata++ Patchmod
short_description: >-
  Optional patch mod that allows content in Arcana and Cataclysm++ to interact
  with each other.
author:
  - Chaosvolt
  - Noctifer
license: CC-BY-SA-3.0
homepage: >-
  https://github.com/chaosvolt/cdda-arcana-mod/tree/master/Patchmods/BN_Arcana_Cata++_Patch
version: 0.0.0
source:
  type: github_archive
  url: "https://github.com/chaosvolt/cdda-arcana-mod/archive/refs/heads/master.zip"
  commit_sha: 37718985431bdbfbee1488e23747edbed3440cbf
  extract_path: Patchmods/BN_Arcana_Cata++_Patch
categories:
  - misc_additions
dependencies:
  bn: ">=0.9.1"
  arcana: "*"
  cata++: "*"
autoupdate:
  type: commit
  branch: master
last_updated: "2025-12-09T16:59:22.488Z"
parent: arcana
