schema_version: "1.0"
id: arcana
display_name: Arcana and Magic Items
short_description: >-
  Adds a host of craftable magic items and spells, centered around the use of
  Arcana skill to research and exploit otherworldly monsters and anomalies.
author:
  - Chaosvolt
license: CC-BY-SA-3.0
homepage: "https://github.com/chaosvolt/cdda-arcana-mod/tree/master/Arcana_BN"
version: 0.0.0
source:
  type: github_archive
  url: "https://github.com/chaosvolt/cdda-arcana-mod/archive/refs/heads/master.zip"
  commit_sha: 37718985431bdbfbee1488e23747edbed3440cbf
  extract_path: Arcana_BN
categories:
  - content
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
last_updated: "2025-12-08T17:38:23.160Z"
