schema_version: "1.0"
id: arts_guns
display_name: Artyoms' Gun Emporium - Reloaded
short_description: Adds all the guns that YOU need to survive the Cataclysm
author:
  - "Artyom177, Leon713, and /u/chieflean"
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Artyom_Emporium_v.1
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Artyom_Emporium_v.1
categories:
  - items
autoupdate:
  type: commit
  branch: master
