schema_version: "1.0"
id: battle_maid
display_name: Battle Maid Redux
short_description: >-
  Translated and tweaked version of the original Battle Maid mod, newly
  revamped. Adds a friendly Shoggoth maid NPC along with lots of maid related
  gear. See README.md for details
author:
  - Vermilion
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Battle_Maid_Redux
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Battle_Maid_Redux
categories:
  - content
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
