schema_version: "1.0"
id: bl9_100monres
display_name: BL9-100%-monster-resilience-version
short_description: |-
  Gigantic sci-fi action adventure expansion mod
   PLEASE, SET 'Monster evolution scaling factor' DURING IN-GAME WORLD GENERATION AROUND 5.00 FOR PROPER GAMEPLAY EXP
author:
  - "Mrsecretguy1/Kenan, Axema Vales, Goat-God"
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/BL9-100%_monster_resilience_version
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/BL9-100%_monster_resilience_version
categories:
  - content
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
