schema_version: "1.0"
id: crazy_labs
display_name: Crazy Labs
short_description: >-
  A mod that adds lots of tough monsters to lab monster gen. Now labs are
  endgame areas! Intended for players who find labs too easy or boring. Inspired
  by Half-Life and the labs in Resident Evil 2.
author:
  - Mewb
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/Medium-Maintenance-Small-Mods/crazy_labs
version: 2025.12.27-142b53b
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/Medium-Maintenance-Small-Mods/crazy_labs
categories:
  - creatures
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
last_updated: "2025-12-27T02:00:12.800Z"
