schema_version: "1.0"
id: gourmand_sgraces
display_name: Gourmand's Graces
short_description: >-
  Greatly expands the selection of various cooked food you can find in grocery
  stores and pharmacy fridges. Focuses on items you'd expect to find in bakery
  and deli departments.
author:
  - KantoJolto
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/GourmandsGraces
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/GourmandsGraces
categories:
  - items
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
