schema_version: "1.0"
id: heavy_miners
display_name: Roadheader and other mining vehicles
short_description: "Adds a roadheader mining vehicle and its parts. Requires Tankmod: Revived."
author:
  - Ckpyt
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/HeavyMining
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/HeavyMining
categories:
  - vehicles
dependencies:
  bn: ">=0.9.1"
  Tankmod_Revived: "*"
autoupdate:
  type: commit
  branch: master
