schema_version: "1.0"
id: jury_rigged_robots
display_name: Jury-Rigged Robots
short_description: >-
  Adds various options for salvaging, jury rigging, and reprogramming broken
  robots.
author:
  - "Sunshine, TheSalamanderDJ"
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Jury_Rigged_Robots
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Jury_Rigged_Robots
categories:
  - misc_additions
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
