schema_version: "1.0"
id: mkmaxxi_s_gunslinger_mod
display_name: Gunslinger Mod
short_description: >-
  Adds a bionic and a non bionic variant of a gunslinger profession. Become the
  fastest gun in the cataclysm.
author:
  - MkMaxxi
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/Medium-Maintenance-Small-Mods/MkMaxxi_Gunslinger_Mod
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/Medium-Maintenance-Small-Mods/MkMaxxi_Gunslinger_Mod
categories:
  - rebalance
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
