schema_version: "1.0"
id: more_survivor_stuff
display_name: More Survivor Stuff
short_description: "Adds more variety to survivor equipment, styles, crafts etc."
author:
  - hoovytaurus
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/More_Survivor_Stuff
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/More_Survivor_Stuff
categories:
  - misc_additions
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
