schema_version: "1.0"
id: mutation_changes1
display_name: Mutation Changes Snofielf
short_description: >-
  Changes, rebalances and adds some more mutations. This a fixed version for the
  fixed version to cleanse the mod of even more old bugs and problems. It also
  has some new mutations and additions.
author:
  - Peeved Penguin (Original Author)
  - Bl4nk (Fixer)
  - Snofielf (Fixer)
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Mutation_Changes_Snofielf_Patch
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Mutation_Changes_Snofielf_Patch
categories:
  - rebalance
autoupdate:
  type: commit
  branch: master
