schema_version: "1.0"
id: mxoudpcosmetics
display_name: "Hair and Skin Color Cosmetics, UDP and MXotto+ version p10"
short_description: Hair and skin color related traits for UDP and MXotto+. p10 sprites by xotto
author:
  - Fuji
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/XottoCosmeticsmod
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/XottoCosmeticsmod
categories:
  - graphical
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
