schema_version: "1.0"
id: mycus_tomodati
display_name: Mycus mod
short_description: For those who want to play as a mycus.
author:
  - Mikazu
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/mycus
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/mycus
categories:
  - misc_additions
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
