schema_version: "1.0"
id: necromancy
display_name: Necromancy
short_description: Adds the ability to revive creatures as minions.
author:
  - dambuk1
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/necromancy
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/necromancy
categories:
  - magical
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
