schema_version: "1.0"
id: oa_early_game_mutations_mod
display_name: Oa's Early Game Mutations mod
short_description: >-
  Makes mutagens available early game. Adds a new building, as well as two start
  scenarios and a profession for it.
author:
  - Oa
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/oa_early_game_mutations_mod
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/oa_early_game_mutations_mod
categories:
  - buildings
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
