schema_version: "1.0"
id: projectkawaii
display_name: ProjectKawaii
short_description: >-
  This mod includes Kawaii high-tech transformable melee weapons, a
  remotely-accessable store via crafting, and of course, cute outfits for maids.
author:
  - inoue&Derp
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Project_Kawaii
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Project_Kawaii
categories:
  - items
autoupdate:
  type: commit
  branch: master
