schema_version: "1.0"
id: red_s_odd_additions
display_name: Red's Odd Additions
short_description: >-
  Adds some rather VERY OP items-test-stuff, odd creatures, and such to the
  game. USE ONLY IF YOU ENJOY VERY OP ITEMS AND WACKINESS OR ONLY IF YOU ARE
  TESTING
author:
  - redxlaser15
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Red's_Odd_Additions
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Red's_Odd_Additions
categories:
  - misc_additions
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
