schema_version: "1.0"
id: tamu
display_name: Targeted Mutations
short_description: >-
  Adds the ability to make serums that will give you one specific mutation, as
  well as introducing a recipe for making the targeted purifier. I've chosen to
  only give a few bad mutations targeted mutati
author:
  - MutaMan
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Targeted
  Mutations
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Targeted
    Mutations
categories:
  - rebalance
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
