schema_version: "1.0"
id: uekibati_mod
display_name: Growable Various Plants Flowerpot (uekibati) mod
short_description: >-
  This mod adds flowerpots in which 37 various plants can grow ranging from
  grains to fruits, vegetables, berries, herbs.
author:
  - Fire man - Translated by Chesthole
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Growable_Various_Plants_Uekibati_mod
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Growable_Various_Plants_Uekibati_mod
categories:
  - items
autoupdate:
  type: commit
  branch: master
