schema_version: "1.0"
id: wildliving
display_name: Wild Living
short_description: >-
  Expansion mod that brings more life and variety to the wilds. Merged with
  Dried Fruits mod by Wayticus as well. Includes tons of new items with recipes
  for enhanced wild living along with an ability t
author:
  - LambdaSix
  - Wayticus
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Wild_Living
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Wild_Living
categories:
  - content
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
