schema_version: "1.0"
id: xeas
display_name: XEAS
short_description: >-
  Adds new Xeno-Adapted Stuff. Close to hi-tech content. Includes an armor set
  (slightly better protection than survival armor, less encumbrance), a new
  knife (better butchering, impression damage) and
author:
  - MrJet
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/XEAS
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/XEAS
categories:
  - items
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
