schema_version: "1.0"
id: xeno_sas4
display_name: Xeno's SAS4 weapons pack
short_description: >-
  Adds all the weapons included inside the game SAS4 Zombie assault, only the
  base quality is present (aka, no red, no black), please do consider that these
  weapons are not a property of mine, and as th
author:
  - xXenocage
license: ALL-RIGHTS-RESERVED
homepage: >-
  https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Xenos_sas4_weapons_pack
version: 0.0.0
source:
  type: github_archive
  url: >-
    https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip
  commit_sha: 142b53ba0079e9c0aea3e8e674ad17a7dc193d07
  extract_path: >-
    Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Xenos_sas4_weapons_pack
categories:
  - items
dependencies:
  bn: ">=0.9.1"
autoupdate:
  type: commit
  branch: master
